version: '3'

services:
  postgres:
    image: postgres:13.4
    container_name: 'java-postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: MrShim
      POSTGRES_USER: postgres
      POSTGRES_DB: HotelBooking


  app:
    build: ./
    container_name: 'hotel-booking'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - 'postgres:my_postgres'


